// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjxiqc3e_Ym-8fDo7TaLRpqpRG4UfSqpQ',
    appId: '1:114710644373:web:e4ba60d40a42b79bbbbd9c',
    messagingSenderId: '114710644373',
    projectId: 'warmindo-9c8e3',
    authDomain: 'warmindo-9c8e3.firebaseapp.com',
    storageBucket: 'warmindo-9c8e3.appspot.com',
    measurementId: 'G-7M2F6FD58L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVWkKZTWtTGnNDlhzTaQVvVOv2lclxGMQ',
    appId: '1:114710644373:android:1eace82175fd0a8bbbbd9c',
    messagingSenderId: '114710644373',
    projectId: 'warmindo-9c8e3',
    storageBucket: 'warmindo-9c8e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBye17RtSh5dthG89Xd1WK1spGHqtq0TnA',
    appId: '1:114710644373:ios:c2e26b4b57eb3aefbbbd9c',
    messagingSenderId: '114710644373',
    projectId: 'warmindo-9c8e3',
    storageBucket: 'warmindo-9c8e3.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBye17RtSh5dthG89Xd1WK1spGHqtq0TnA',
    appId: '1:114710644373:ios:2e087598fc5fd110bbbd9c',
    messagingSenderId: '114710644373',
    projectId: 'warmindo-9c8e3',
    storageBucket: 'warmindo-9c8e3.appspot.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
